# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='/Users/jacobo/dev/dixit/server/src/../../cards')),
                ('name', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'cards',
                'verbose_name': 'card',
            },
        ),
        migrations.CreateModel(
            name='CardDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('confidence', models.IntegerField(default=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='game.Card')),
            ],
            options={
                'verbose_name_plural': 'card descriptions',
                'verbose_name': 'card description',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('ongoing', 'ONGOING'), ('finished', 'FINISHED'), ('abandoned', 'ABANDONED')], default='new', max_length=16)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_on',),
                'verbose_name_plural': 'games',
                'verbose_name': 'game',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(max_length=256, null=True)),
                ('card_chosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to='game.Card')),
                ('card_provided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='game.Card')),
            ],
            options={
                'verbose_name_plural': 'play',
                'verbose_name': 'play',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('cards', models.ManyToManyField(related_name='played_by', to='game.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Game')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name_plural': 'player',
                'verbose_name': 'player',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'NEW'), ('pending', 'PENDING'), ('complete', 'COMPLETE')], default='new', max_length=16)),
                ('number', models.IntegerField(default=0)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_round_play', to='game.Card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.Game')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name_plural': 'round',
                'verbose_name': 'round',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='game.Round'),
        ),
        migrations.AddField(
            model_name='play',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('game', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('game', 'name'), ('game', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together=set([('game_round', 'player')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='play',
            order_with_respect_to='player',
        ),
    ]
